apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: some-name
spec:
  template:
    spec:
      containers:
        - image: gcr.io/project/some-name:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
